import Keanu from "../../img/keanu.jpeg";
import Tanjiro from "../../img/tanjiro.jpg";
import Hitomi from "../../img/hitomi.jpg";
import Adele from "../../img/adele.jpg";
import Nayya from "../../img/nayya.png";

const lotsOfData = [
  {
    id: 1,
    ava: "A",
    img: Adele,
    nama: "Adel",
    sabuk: "Sabuk Kuning",
    alpa: 2,
    sakit: 0,
    izin: 0,
    present: "75%",
  },
  {
    id: 2,
    ava: "A",
    nama: "Aldi",
    sabuk: "Sabuk Kuning",
    alpa: 0,
    sakit: 0,
    izin: 1,
    present: "88%",
  },
  {
    id: 3,
    ava: "A",
    img: Keanu,
    nama: "Angga",
    sabuk: "Sabuk Putih",
    alpa: 1,
    sakit: 0,
    izin: 0,
    present: "92%",
  },
  {
    id: 4,
    ava: "C",
    img: Hitomi,
    nama: "Chika",
    sabuk: "Sabuk Putih",
    alpa: 0,
    sakit: 0,
    izin: 0,
    present: "95%",
  },
  {
    id: 5,
    ava: "F",
    nama: "Fito",
    sabuk: "Sabuk Hijau",
    alpa: 0,
    sakit: 7,
    izin: 3,
    present: "70%",
  },
  {
    id: 6,
    ava: "G",
    img: Tanjiro,
    nama: "Gilang",
    sabuk: "Sabuk Hijau",
    alpa: 0,
    sakit: 1,
    izin: 0,
    present: "80%",
  },
  {
    id: 7,
    ava: "N",
    img: Nayya,
    nama: "Nayya",
    sabuk: "Sabuk Biru",
    alpa: 0,
    sakit: 3,
    izin: 1,
    present: "78%",
  },
  {
    id: 8,
    ava: "P",
    nama: "Putri",
    sabuk: "Sabuk Coklat",
    alpa: 0,
    sakit: 0,
    izin: 1,
    present: "90%",
  },
  {
    id: 9,
    ava: "S",
    nama: "Sahrul",
    sabuk: "Sabuk Putih",
    alpa: 10,
    sakit: 0,
    izin: 2,
    present: "50%",
  },
  {
    id: 10,
    ava: "S",
    nama: "Salwa",
    sabuk: "Sabuk Hitam",
    alpa: 1,
    sakit: 0,
    izin: 2,
    present: "85%",
  },
];
export default lotsOfData;
// export const totalKarateka = [2.192];
// export const ketKarateka = [{ sakit: 12 }, { izin: 2 }, { alpa: 3 }];
